### ISSUE TITLE
Site colorswitch broken

### ISSUE THREAD

**Issue by dhwanishah** [alfalfascout/NineSquares#12]
I haven't looked at the changes you made since the last time I PRd, but the colorswitch on the site is now broken and also the styling is off. Site updated?

**Comment by alfalfascout** [comment]
Broken how? It works fine for me. Also, off in what way(s)?

**Comment by dhwanishah** [comment]
Ahh ok, so it took me a sec to figure it from my logs, but my SSH keys expired on my dev box so my cron script never did a git pull successfully this morning and somehow only update half of the code so obviously it won't work. I should really add a fail message to the script haha...so nvm, ur good. sorry for scaring u lol

**Comment by alfalfascout** [comment]
No problem. Another issue solved by our crack team.

**Comment by dhwanishah** [comment]
yay :+1:
