### ISSUE TITLE
Add more color choices in web app

### ISSUE THREAD

**Issue by alfalfascout** [alfalfascout/NineSquares#3]
Add more color schemes, maybe like the attached pictures, to the web app. 
Be sure to follow the example of the existing code in colors.js, main.css, and index.html's color choice section.

![checkers](https://cloud.githubusercontent.com/assets/9934097/10258594/7148625c-692d-11e5-855f-ae34d90c4f55.png)
![gentle pinkle](https://cloud.githubusercontent.com/assets/9934097/10258589/71470024-692d-11e5-8e06-c55a3546fbd1.png)
![purple dragon](https://cloud.githubusercontent.com/assets/9934097/10258592/71474d5e-692d-11e5-807a-dc4736a5eb92.png)
![silver gold](https://cloud.githubusercontent.com/assets/9934097/10258590/7147329c-692d-11e5-8ae0-131725191c76.png)
![thats a happy sapling](https://cloud.githubusercontent.com/assets/9934097/10258591/71475088-692d-11e5-8276-2e6ee7b91707.png)
![white gold](https://cloud.githubusercontent.com/assets/9934097/10258593/71487be8-692d-11e5-80b2-4a94bf9e1be0.png)

**Comment by dhwanishah** [comment]
What are the names of each of the color pairs?

**Comment by dhwanishah** [comment]
I've written the code and created a PR that's currently unfinished since I still need the color pair names. Will change it, once received. Here's the PR: https://github.com/alfalfascout/NineSquares/pull/9

**Comment by alfalfascout** [comment]
My friend actually made these images. In the order shown, the palettes were named: checkers, gentle pinkle, purple dragon, silver gold, that's a happy sapling, and white gold. If you have any improvements to the color schemes, I would welcome them.

**Comment by alfalfascout** [comment]
Solved by pull request #9
